language: node_js
node_js:
  - "4"
  - "5"
  - "6"
env:
  global:
  - CXX=g++-4.8
  - SAUCE_USERNAME=react-es6-redux
  - SAUCE_ACCESS_KEY=e5996a82-a35b-4707-b324-79fe310d5ab3
addons:
  sauce_connect: true
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_script:
  - npm run build-prod-all-owner
  - npm run build-travis
  - "npm run serve-dist > /dev/null &"
script:
  - echo "UNIT TESTS - via karma - with code coverage"
  - npm test
  - echo "UNIT TESTS - via mocha"
  - npm run mocha
  - echo "END 2 END TESTS - via protractor / through SauceLabs"
  - npm run test-e2e -- --port 3000
after_success:
  - cat ./build/reports/coverage/**/lcov.info | ./node_modules/.bin/coveralls
